
services:
    - docker:18-dind

variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

workflow:
    rules:
        - if: $CI_COMMIT_TAG
        - if: $CI_COMMIT_BRANCH
        - if: $CI_MERGE_REQUEST_IID

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - build

stages:
    - build
    - test


build:
    image: node:16
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    stage: build
    script:
        - echo "CI_COMMIT_REF_NAME $CI_COMMIT_REF_NAME"
        - echo "CI_DEFAULT_BRANCH $CI_DEFAULT_BRANCH"
        - echo "GITLAB_ENV $GITLAB_ENV"
        - echo "UBIQ_TEST_DATA_FILE $UBIQ_TEST_DATA_FILE"
        - echo "UBIQ_MAX_AVG_ENCRYPT $UBIQ_MAX_AVG_ENCRYPT"
        - echo "UBIQ_MAX_AVG_DECRYPT $UBIQ_MAX_AVG_DECRYPT"
        - echo "UBIQ_MAX_TOTAL_ENCRYPT $UBIQ_MAX_TOTAL_ENCRYPT"
        - echo "UBIQ_MAX_TOTAL_DECRYPT $UBIQ_MAX_TOTAL_DECRYPT"
        - npm install

.tests:
    image: node:16
    stage: test
    script:
        - npm install
        - npm test

# Run tests for variables in the ALL or feature environment
test_feature:
    extends: .tests
    rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
    environment: feature

# Run tests for variables in the ALL or master environment
test_master:
    extends: .tests
    rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    environment: master

sast:
    variables:
        SAST_EXCLUDED_PATHS: node_modules
    stage: test
include:
    - template: Security/SAST.gitlab-ci.yml

